name: Daily Data Pre-check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write 

jobs:
  check_data:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.compare.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Restore previous hash
        id: restore
        uses: actions/cache/restore@v4
        with:
          path: .last_data_hash
          key: prem-data-hash

      - name: Compute hash
        id: hash
        run: |
          curl -s https://fantasy.premierleague.com/api/fixtures > data.json
          new_hash=$(sha256sum data.json | cut -d' ' -f1)
          echo "new_hash=$new_hash" >> $GITHUB_OUTPUT
          echo "Current hash: $new_hash"

      - name: Check if changed
        id: compare
        run: |
          echo "Checking if data has changed..."

          # Get previous hash
          if [ -f .last_data_hash ]; then
            previous_hash=$(cat .last_data_hash)
            echo "Previous hash found: $previous_hash"
          else
            previous_hash=""
            echo "No previous hash found."
          fi

          current_hash="${{ steps.hash.outputs.new_hash }}"
          echo "Current hash: $current_hash"

          if [ -n "$previous_hash" ] && [ "$previous_hash" = "$current_hash" ]; then
            echo "Data is unchanged."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Data has changed (or no previous hash exists)."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Save new hash file
        run: echo "${{ steps.hash.outputs.new_hash }}" > .last_data_hash

      - name: Save hash to cache
        uses: actions/cache/save@v4
        with:
          path: .last_data_hash
          key: prem-data-hash

  generate_table:
    needs: check_data
    if: ${{ needs.check_data.outputs.changed == 'true' }}
    uses: ./.github/workflows/generate-table.yml
    secrets:
      MY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
