name: Generate and Commit Table

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" 

permissions:
  contents: write 

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # or any other library your script needs

      - name: Clean History_GH folder
        run: rm -rf History_GH/*

      - name: Run image generator
        run: |
          python generate_tables.py  # your script should save to e.g. output/image.png

      - name: Commit and push image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add History_GH/
          git commit -m "Auto-generated image $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
